package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"text/template"
)

func main() {
	const output = "encode_test.go"

	f, err := os.Create(output)
	if err != nil {
		log.Fatalf("Failed to create file %s: %v", output, err)
	}
	defer f.Close()

	tmpl := template.Must(template.New("encode_test").Parse(testTemplate))
	if err := tmpl.Execute(f, nil); err != nil {
		log.Fatalf("Failed to execute template: %v", err)
	}

	fmt.Printf(">>>>>>>>>>>>> models:%v\n", models)
	log.Printf("Generated %s", filepath.Base(output))
}

const testTemplate = `// Code generated by .codegen/generate.go; DO NOT EDIT.

package codec

import (
    "testing"
)

func TestGetControllerResponse_JSON(t *testing.T) {
    // TODO: Add tests for JSON marshalling/unmarshalling of GetControllerResponse
}
`
