// Code generated by .codegen/generate.go; DO NOT EDIT.

package codec

import (
	"testing"
)

func TestGetControllerResponse_JSON(t *testing.T) {
	// TODO: Add tests for JSON marshalling/unmarshalling of GetControllerResponse
}
